# Generated by Django 5.0.7 on 2024-07-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
